In [11]:
import sys
from pathlib import Path
import pandas as pd
import requests
import matplotlib.pyplot as plt

project_root = Path.cwd().parent
sys.path.insert(0, str(project_root))

from src.config import load_yaml_config
from src.data import download_data, load_data_from_json

config = load_yaml_config(project_root / "config.yaml")
city = "Lisboa"

In [12]:
# Download data if it isn't already downloaded
download_data(city, config)

HTTP status: 200
Request URL: https://archive-api.open-meteo.com/v1/archive?latitude=38.7223&longitude=-9.1393&start_date=2020-01-01&end_date=2025-12-31&hourly=temperature_2m%2Crelative_humidity_2m%2Cprecipitation%2Cwind_speed_10m&timezone=Europe%2FLisbon

In [13]:
# Load data into a DataFrame
df = load_data_from_json(city, config)

In [14]:
display(df)

,time,temperature_2m,relative_humidity_2m,precipitation,wind_speed_10m
0,2020-01-01 00:00:00,8.6,95,0.0,6.7
1,2020-01-01 01:00:00,10.0,92,0.0,7.7
2,2020-01-01 02:00:00,9.2,94,0.0,7.4
3,2020-01-01 03:00:00,9.2,94,0.0,8.1
4,2020-01-01 04:00:00,9.0,95,0.0,8.9
...,...,...,...,...,...
52603,2025-12-31 19:00:00,10.4,86,0.0,6.1
52604,2025-12-31 20:00:00,10.4,87,0.0,5.7
52605,2025-12-31 21:00:00,10.6,87,0.0,5.5
52606,2025-12-31 22:00:00,10.5,89,0.0,9.0
52607,2025-12-31 23:00:00,10.2,87,0.0,10.1

In [15]:
# Get the information of all data types present in the DataFrame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 52608 entries, 0 to 52607
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time                  52608 non-null  datetime64[us]
 1   temperature_2m        52608 non-null  float64
 2   relative_humidity_2m  52608 non-null  int64
 3   precipitation         52608 non-null  float64
 4   wind_speed_10m        52608 non-null  float64
dtypes: datetime64[us](1), float64(3), int64(1)
memory usage: 2.0 MB

In [16]:
# Check the statistical summary
df.describe()

,time,temperature_2m,relative_humidity_2m,precipitation,wind_speed_10m
count,52608,52608.000000,52608.000000,52608.000000,52608.000000
mean,2022-12-31 23:30:00,17.275540,74.434877,0.074584,12.731623
min,2020-01-01 00:00:00,1.500000,14.000000,0.000000,0.000000
25%,2021-07-01 23:45:00,13.600000,63.000000,0.000000,7.800000
50%,2022-12-31 23:30:00,16.900000,78.000000,0.000000,12.000000
75%,2024-07-01 23:15:00,20.200000,89.000000,0.000000,16.700000
max,2025-12-31 23:00:00,40.700000,100.000000,19.200000,48.800000
std,NaN,5.285831,17.044434,0.437635,6.400850